runtime: nodejs20

instance_class: F1

env_variables:
  # DO NOT hardcode your database URL here if your repository is public!
  # Instead, set this variable directly in your Google Cloud console.
  DATABASE_URL: "YOUR_NEON_DATABASE_URL"
  SESSION_SECRET: "YOUR_SESSION_SECRET"
  NODE_ENV: "production"
  PORT: "8080"
